import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const objectSans = localFont({
  src: "../public/fonts/PPObjectSans-Regular.otf",
  variable: "--font-object-sans",
  display: "swap",
});

const neueMontreal = localFont({
  src: "../public/fonts/PPNeueMontreal-Medium.otf",
  variable: "--font-neue-montreal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${objectSans.variable} ${neueMontreal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
